# Generated by Django 4.2.6 on 2023-10-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=100)),
                ("idade", models.IntegerField()),
            ],
        ),
    ]
